name: Install libs to document
description: Install Cylc libs and Rose

inputs:
  # If these are not specified, they fall back to the workflow_dispatch input
  # values, or failing that, 'master'
  cylc-flow-tag:
    description: 'cylc-flow github release tag (must be present in cylc-docs)'
    required: false
  cylc-rose-tag:
    description: 'cylc-rose github release tag'
    required: false
  cylc-uis-tag:
    description: 'cylc-uiserver github release tag'
    required: false
  metomi-rose-tag:
    description: 'rose github release tag (currently only affects cylc-rose install)'
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      env:
        cylc_flow: ${{ inputs.cylc-flow-tag || github.event.inputs.cylc-flow-tag || 'master' }}
        meto_rose: ${{ inputs.metomi-rose-tag || github.event.inputs.metomi-rose-tag || 'master' }}
        cylc_rose: ${{ inputs.cylc-rose-tag || github.event.inputs.cylc-rose-tag || 'master' }}
        cylc_uis: ${{ inputs.cylc-uis-tag || github.event.inputs.cylc-uis-tag || 'master' }}
      run: |
        pip install \
          "cylc-flow[all] @ git+https://github.com/cylc/cylc-flow@${cylc_flow}" \
          "cylc-uiserver[all] @ git+https://github.com/cylc/cylc-uiserver@${cylc_uis}" \
          "metomi-rose[all] @ git+https://github.com/metomi/rose@${meto_rose}" \
          "cylc-rose[all] @ git+https://github.com/cylc/cylc-rose@${cylc_rose}"
      # NOTE: Install with [all] so we can import plugins which may
      # have extra dependencies.
