name: Sync PR

on:
  push:
    branches:
      - '8.*.x'
  schedule:
    - cron: '11 11 * * 0' # every Sunday at 11:11
  workflow_dispatch:
    inputs:
      head_branch:
        description: Branch to merge into master
        required: true

jobs:
  sync:
    uses: cylc/release-actions/.github/workflows/branch-sync.yml@v1
    with:
      head_branch: ${{ inputs.head_branch }}
    secrets: inherit
